version: '3.8'

services:
  kipkid-api:
    image: kipkid_api
    container_name: kipkid
    build:
      context: .
    ports:
      - 8080:8080
      - 9229:9229
    env_file:
      - .env.production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

