version: '3.8'

services:
  kipkid-api:
    image: kipkid_api
    container_name: kipkid
    build:
      context: .
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - .env.production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=adonis
